#!/usr/bin/env node

/*!
    Copyright 2019 SOLTECSIS SOLUCIONES TECNOLOGICAS, SLU
    https://soltecsis.com
    info@soltecsis.com


    This file is part of FWCloud (https://fwcloud.net).

    FWCloud is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    FWCloud is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with FWCloud.  If not, see <https://www.gnu.org/licenses/>.
*/

const chalk = require('chalk');
const fs = require('fs-extra');
const path = require('path');
const child_process = require('child_process');
const series = require('async');

function error(message) {
    process.stderr.write("\n");
    process.stderr.write(chalk.bgRed.bold.white(`${message}\n`));
    process.stderr.write("\n");
}

async function main()
{
    const cliPath = path.join(process.cwd(), 'dist', 'src', 'cli', 'cli.js');

    if (!fs.existsSync(path.join(process.cwd(), 'fwcli'))) {
        throw new Error('fwcli not found in ' + process.cwd());
    }

    if (!fs.existsSync(path.join(process.cwd(), 'node_modules'))) {
        throw new Error(`node_modules not found. Please run "npm install" first.`);
    }

    process.stdout.write('Starting compilation...');
    const stdout = child_process.execSync('npm run smart-compilation');
    
    if (stdout.toString().match(/Compiling all files.../) || stdout.toString().match(/Needs compilation.../)) {
        process.stdout.write(chalk.bold.green('done'));
    } else {
        process.stdout.write(chalk.bold.blueBright('[not required]'));
    }

    console.log("\n");
    return new Promise((resolve, reject) => {
        const cli = child_process.fork(`${cliPath}`, [...process.argv.slice(2)]);

        cli.on('error', (err) => {
            reject(error);
        });

        cli.on('close', (code) => {
            resolve(code);
        });
    });
}

main().then((code) => {
    process.exit(code);
}).catch(err => {
    error(err.message);
    process.exit(1);
});